spring.application.name=storedb

#Perfil local para cargar la configuracion privada
spring.profiles.active=local

#Configuracion JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Puerto del servidor
server.port=8080
